version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-python-flask
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install autoconf
            sudo apt-get install autotools-dev

      - run:
          command: |
            echo "Hello"
destination: tr1
