version: 2.1

jobs:
  automatic-testing:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "install dependencies"
          command: |
            sudo apt-get update
            sudo apt-get install cmake
            sudo apt-get install autoconf
            sudo apt-get install autotools-dev
            sudo apt-get install libtool
      - run:
          name: "automatic testing"
          command: |
            git submodule update --init --recursive
            mkdir out
            cd out
            cmake ../module1
            sudo make
            sudo make install
            export LD_LIBRARY_PATH=/usr/local/lib/
            timeKeeper_test1
            smsDevice_test1
            smsSender_test1
            sudo smsPlanner_test1
            timeKeeper_test2
            smsDevice_test2
            smsSender_test2
            sudo smsPlanner_test2
            echo -e "add_definitions(-DIntegrationTests)\n$(cat ../module1/CMakeLists.txt)" > ../module1/CMakeLists.txt
            rm -rf CMakeFiles CMakeCache.txt
            cmake ../module1
            sudo make
            sudo make install
            timeKeeper_test1
            smsDevice_test1
            smsSender_test1
            sudo smsPlanner_test1
            timeKeeper_test2
            smsDevice_test2
            smsSender_test2
            sudo smsPlanner_test2

workflows:
  automatic-testing-workflow:
    jobs:
      - automatic-testing

