version: 2.1

jobs:
  automatic-testing:
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "install dependencies"
          command: |
            sudo apt-get update
            sudo apt-get install cmake
            sudo apt-get install autoconf
            sudo apt-get install autotools-dev
            sudo apt-get install libtool
      - run:
          name: "install project"
          command: |
            git submodule update --init --recursive
            mkdir out
            cd out
            cmake -DDESTDIR=${PWD}/out ../module1
            make DESTDIR=${PWD}/out
            make install DESTDIR=${PWD}/out
            export LD_LIBRARY_PATH=out/usr/local/lib/


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  automatic-testing-workflow:
    jobs:
      - automatic-testing

