version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-automatic-testing
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - run:
          command: |
            echo "Hello"

      - run:
          command: |
            echo "Hello"
destination: tr1
